// Generators for the two modules Tarantula adds to every instant deploy.
//
// An instant app is uploaded straight to the Workers script API, which has no
// Static Assets support and no `wrangler.jsonc` to declare an ASSETS binding.
// So the control plane ships the app's files inside the bundle and hands the
// user's Worker an ASSETS binding that behaves like the real one: run the
// Worker first, fall back to the asset, then fall back to the index document.
//
// Both functions are pure string builders. Nothing here executes user code.

const contentTypes = {
  html: "text/html; charset=utf-8",
  css: "text/css; charset=utf-8",
  js: "text/javascript; charset=utf-8",
  svg: "image/svg+xml",
  png: "image/png",
  ico: "image/x-icon",
  txt: "text/plain; charset=utf-8",
  json: "application/json; charset=utf-8",
  woff2: "font/woff2",
};

const fallbackContentType = "application/octet-stream";

export const assetsModuleName = "_tarantula_assets.mjs";
export const shimModuleName = "_tarantula_shim.mjs";

// `assets` maps a "/"-prefixed request path to base64 file contents.
export function buildAssetsModule(assets) {
  const entries = Object.keys(assets)
    .sort()
    .map((path) => `  ${JSON.stringify(path)}: ${JSON.stringify(assets[path])},`)
    .join("\n");
  return `// Generated by Tarantula instant hosting. Do not edit.
const encoded = {
${entries}
};

const contentTypes = ${JSON.stringify(contentTypes, null, 2)};

const decoded = new Map();

export function hasAsset(path) {
  return Object.hasOwn(encoded, path);
}

export function assetBytes(path) {
  if (!Object.hasOwn(encoded, path)) return null;
  if (!decoded.has(path)) {
    const binary = atob(encoded[path]);
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index += 1) {
      bytes[index] = binary.charCodeAt(index);
    }
    decoded.set(path, bytes);
  }
  return decoded.get(path);
}

export function assetType(path) {
  const dot = path.lastIndexOf(".");
  const extension = dot === -1 ? "" : path.slice(dot + 1).toLowerCase();
  return contentTypes[extension] ?? ${JSON.stringify(fallbackContentType)};
}

export default encoded;
`;
}

export function buildShim(entryBasename) {
  return `// Generated by Tarantula instant hosting. Do not edit.
import userWorker from ${JSON.stringify(`./${entryBasename}`)};
import { assetBytes, assetType, hasAsset } from ${JSON.stringify(`./${assetsModuleName}`)};

const indexPath = "/index.html";

function assetResponse(path) {
  const bytes = assetBytes(path);
  if (!bytes) return null;
  return new Response(bytes, {
    headers: {
      "content-type": assetType(path),
      "cache-control": path.endsWith(".html")
        ? "no-cache"
        : "public, max-age=31536000, immutable",
    },
  });
}

function assetPathFor(pathname) {
  if (pathname === "/") return hasAsset(indexPath) ? indexPath : null;
  if (hasAsset(pathname)) return pathname;
  if (pathname.endsWith("/") && hasAsset(pathname + "index.html")) {
    return pathname + "index.html";
  }
  return null;
}

// Stands in for the Static Assets ASSETS binding.
const ASSETS = {
  async fetch(request) {
    const url = new URL(request.url);
    const path = assetPathFor(url.pathname);
    const response = assetResponse(path ?? indexPath);
    if (response) return response;
    return new Response("Not found", {
      status: 404,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  },
};

const shim = {
  async fetch(request, env, ctx) {
    const response = await userWorker.fetch(request, { ...env, ASSETS }, ctx);
    // Mirrors run_worker_first plus single-page-application fallback: the
    // Worker sees every request, and an unhandled non-API GET still gets the
    // static app instead of the Worker's 404.
    if (
      response &&
      response.status === 404 &&
      (request.method === "GET" || request.method === "HEAD")
    ) {
      const url = new URL(request.url);
      if (!url.pathname.startsWith("/api/")) {
        const served = assetResponse(assetPathFor(url.pathname) ?? indexPath);
        if (served) return served;
      }
    }
    return response;
  },
};

if (typeof userWorker.scheduled === "function") {
  shim.scheduled = (event, env, ctx) => userWorker.scheduled(event, env, ctx);
}

export default shim;
`;
}
